// add button
const addShowButton = document.querySelector(".add");
// label for the add button
const showInput = document.querySelector(".add-show input");
// unordered list (not yet visible)
const showList = document.querySelector(".show-list");
// span class for number of favorite shows
const showCount = document.querySelector(".number");

//creating list item and adding to list. ShowList points to ul element. Li element generated by createElement and the entered text added to the end of the ul element with append().
addShowButton.addEventListener("click", function () {
  //show captures the value of the input 
  const show = showInput.value;
  if (show !== "") {
    let listItem = document.createElement("li");
    listItem.innerText = show;
    showList.append(listItem);
    //creating counter of the number of values in the input.
    let shows = document.querySelectorAll(".show-list li");
    showCount.innerText = shows.length;
  }
});
